apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - env-config.yaml
patches:
  - path: replicas-patch.yaml
  - target:
      group: discovery.k8s.io
      version: v1
      kind: EndpointSlice
      name: mysql-windows-host
    patch: |-
      - op: replace
        path: /endpoints/0/addresses/0
        value: 10.46.132.206
