apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bank
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: customer-service
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bank
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: account-service
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bank
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
