apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bank
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bank
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bank
spec:
  replicas: 2
